# ====================n
# Package Manager
# ====================-

[[plugins]]
repo = 'Shougo/dein.vim'
if = 'has("python3")'

# ====================-
# Completion
# ====================-

# for NVIM
# [[plugins]]
# repo = 'Shougo/deoplete.nvim'
# if = 'has("python3")'
# on_i = 1

# # for VIM
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

# [[plugins]]
# repo = 'Shougo/neocomplcache.vim'
# on_i = 1

# [[plugins]]
# repo = 'Valloric/YouCompleteMe'
# on_i = 1
# build = './install.py --tern-completer'

[[plugins]] # カッコの補完など
repo = 'cohama/lexima.vim'
on_i = 1

# ====================-
# Snipetts
# ====================-

# [[plugins]]
# repo = 'SirVer/ultisnips'
# on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1

# ====================-
# FileTree
# ====================-

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['scrooloose/nerdtree']

[[plugins]]
repo = 'ryanoasis/vim-devicons'
depends = ['scrooloose/nerdtree']

# NOTE: ホワイトリストでもくっそ思いのでとりあえず無効化
# [[plugins]]
# repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
# depends = ['scrooloose/nerdtree']

# ====================-
# StatusBar
# ====================-

[[plugins]]
repo = 'bling/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

# ====================-
# Appearance
# ====================-

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

# ====================-
# Syntax checker
# ====================-

[[plugins]]
repo = 'w0rp/ale'

# [[plugins]]
# repo = 'vim-syntastic/syntastic'

# ====================-
# Finder
# ====================-

[[plugins]]
repo = 'Shougo/denite.nvim'
if = 'has("python3")'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['denite.vim']

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_source = ['denite.vim']

# [[plugins]]
# repo = 'ctrlpvim/ctrlp.vim'

# ====================-
# Ctags
# ====================-

[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

# ====================-
# Useful tools
# ====================-

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]] # for searching
repo = 'haya14busa/incsearch.vim'

[[plugins]] # for comment out
repo = 'tyru/caw.vim'

# [[plugins]] # for pasting
# repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'heavenshell/vim-jsdoc'

[[plugins]] # for life log
repo = 'wakatime/vim-wakatime'

# for run command quickly
# <Leader>r
[[plugins]]
repo = 'thinca/vim-quickrun'

# [[plugins]] # for simplifiles
# repo = 'AndrewRadev/splitjoin.vim'

# [[plugins]]
# repo = 'sjl/gundo.vim'

# ====================-
# English
# ====================-

# [[plugins]]
# repo     = 'ujihisa/neco-look'

# ====================-
# Others
# ====================-

# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# build = 'make'
#
#
