# ====================-
# Python
# ====================-

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']
build = 'git submodule update --init'

# [[plugins]]
# repo = "zchee/deoplete-jedi"
# on_ft = ['python']
# build = 'git submodule update --init'

# ====================-
# GO
# ====================-

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
on_i = 1

# [[plugins]]
# repo = 'zchee/deoplete-go'
# on_ft = 'go'
# on_i = 1

# [[plugins]]
# repo = 'Blackrush/vim-gocode'
# on_ft = 'go'

# ====================-
# Rust
# ====================-

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'

# ====================-
# Perl
# ====================-

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['perl']

# ====================-
# TS
# ====================-

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'ts', 'tsx']

# [[plugins]]
# repo = 'Quramy/tsuquyomi'
# on_ft = ['typescript', 'ts', 'tsx']

# [[plugins]]
# repo = 'mhartington/nvim-typescript'
# on_ft = ['typescript', 'ts', 'tsx']

# ====================-
# JS
# ====================-

[[plugins]]
repo = 'pangloss/vim-javascript' # jsインデントとシンタックスカラー
on_ft = ['javascript', 'jsx']

[[plugins]]
repo = 'moll/vim-node' # gfでrequire移動用
on_ft = 'javascript'

# [[plugins]]
# repo = 'mxw/vim-jsx'  # jsxのインデントとシンタックスハイライト, vim-javascriptに依存する
# on_ft = ['javascript', 'jsx']
# on_source = ['vim-javascript']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'  # jsxのシンタックスハイライトとインデント
on_ft = [ 'jsx']
on_source = ['vim-javascript']

# [[plugins]]
# repo  = 'ternjs/tern_for_vim'
# on_ft = ['javascript', 'jsx']
# build = 'npm install'

# [[plugins]]
# repo  = 'carlitux/deoplete-ternjs'
# on_ft = ['javascript', 'jsx']
# build = 'npm install -g tern'

# [[plugins]]
# repo = 'heavenshell/vim-jsdoc' # jsdoc用
# on_ft = 'javascript'

# ====================-
# CS
# ====================-

[[plugins]]
repo = 'kchmck/vim-coffee-script' # use npm coffeelint module
on_ft = 'coffee'

# ====================-
# Markup Langs
# ====================-

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

[[plugins]]
repo = 'mustache/vim-mustache-handlebars' # hbs
on_ft = 'handlebars'

[[plugins]]
repo = 'hail2u/vim-css3-syntax' # css
on_ft = 'css'

[[plugins]]
repo = 'digitaltoad/vim-jade'  # jade
on_ft = 'jade'

[[plugins]]
repo = 'groenewege/vim-less' # less
on_ft = 'less'

[[plugins]]
repo = 'stephpy/vim-yaml' # yaml
on_ft = 'yaml'

[[plugins]]
repo = 'elzr/vim-json' # json
on_ft = 'json'

# ====================-
# Others
# ====================-

[[plugins]]
repo = 'tmux-plugins/vim-tmux' # tmux.conf用
on_ft = 'tmux.conf'

