swipe:
  3:
    left:
      command: 'xdotool key alt+Right'
    right:
      command: 'xdotool key alt+Left'
  4:
    left:
      command: 'xdotool key super+n'
    right:
      command: 'xdotool key super+p'
    up:
      command: 'xdotool key super+j'
    down:
      command: 'xdotool key super+k'
pinch:
  4:
    in:
      command: 'xdotool key super+d'
    out:
      command: 'xdotool key esc'

threshold:
  swipe: 0.1
  pinch: 0.5

interval:
  swipe: 0.5
  pinch: 0.3
