# ====================-
# Syntax checker
# ====================-

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_echo_msg_format = '%severity%: %linter%: %s'
let g:ale_sign_column_always = 1
let g:ale_sign_error = 'E '
let g:ale_sign_warning = 'W '
let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0  " i don't want linters to run on opening a file
let g:ale_statusline_format = ['  %d', '  %d', '  ']
let g:ale_linters = {
      \ 'c': [ 'cppcheck' ],
      \ 'python': ['flake8'],
      \ 'go': [ 'gofmt', 'go vet', 'golint' ],
      \ 'javascript': [ 'eslint' ],
      \ 'jsx': [ 'eslint' ],
      \ 'css': [ 'stylelint' ],
      \ 'html': ['htmlhint'],
      \ }
let g:ale_fixers = {
    \ 'python': ['autopep8', 'black', 'isort'],
    \ }
" For Python
" pip install -U flake8 flake8-import-order autopep8 black isort
'''

# ====================-
# Useful tools
# ====================-

# [[plugins]]
# repo = 'editorconfig/editorconfig-vim'
