# ====================-
# C/C++
# ====================-

[[plugins]]
repo = "justmao945/vim-clang"
on_ft = ['c', 'cpp']
hook_add = '''
let g:clang_auto = 1
let g:clang_c_completeopt = 'menuone'
let g:clang_cpp_completeopt = 'menuone'
let g:clang_c_options = '-std=gnu11'
let g:clang_cpp_options = '-std=c++11 -stdlib=libc++'
'''

# ====================-
# Python
# ====================-

[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

# ====================-
# GO
# ====================-

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
on_i = 1
hook_add = '''
let g:go_fmt_command = "goimports" " save hook process in go-vim, neet to install goimports
let g:syntastic_go_checkers = ['gofmt', 'golint', 'govet']

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_fields = 1
let g:go_highlight_types = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
" let g:go_highlight_build_constraints = 1

" let g:go_def_mapping_enabled=0 " タブ移動の時にnvimでうるさいから
'''

# ====================-
# Rust
# ====================-

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

# ====================-
# Perl
# ====================-

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['perl']

# ====================-
# Ruby/RoR
# ====================-

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# ====================-
# TS
# ====================-

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'ts', 'tsx']


# ====================-
# JS
# ====================-

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'  # jsxのシンタックスハイライトとインデント
on_ft = [ 'jsx']
on_source = ['vim-javascript']

[[plugins]]
repo = 'heavenshell/vim-jsdoc'

# ====================-
# CS
# ====================-

[[plugins]]
repo = 'kchmck/vim-coffee-script' # use npm coffeelint module
on_ft = 'coffee'

# ====================-
# JSON/CSON
# ====================-

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json', 'cson']
hook_add = '''
au BufNewFile,BufRead *.cson setf json
'''

# ====================-
# TOML
# ====================-

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# ====================-
# HTML
# ====================-

[[plugins]]
repo = 'othree/html5.vim'
on_ft = 'html'

# ====================-
# Handlebars
# ====================-

[[plugins]]
repo = 'mustache/vim-mustache-handlebars' # hbs
on_ft = 'handlebars'

# ====================-
# CSS
# ====================-

[[plugins]]
repo = 'hail2u/vim-css3-syntax' # css
on_ft = 'css'

# ====================-
# Jade
# ====================-

[[plugins]]
repo = 'digitaltoad/vim-jade'  # jade
on_ft = 'jade'

# ====================-
# Less
# ====================-

[[plugins]]
repo = 'groenewege/vim-less' # less
on_ft = 'less'

# ====================-
# Yaml
# ====================-

[[plugins]]
repo = 'stephpy/vim-yaml' # yaml
on_ft = 'yaml'

# ====================-
# Tmux
# ====================-

[[plugins]]
repo = 'tmux-plugins/vim-tmux' # tmux.conf用
on_ft = 'tmux.conf'

# ====================-
# Terraform
# ====================-

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['tf', 'tfvars']
hook_add = '''
let g:terraform_fmt_on_save = 0 " to fit the rule of certain pj
'''
